# -*- coding: utf-8 -*-
"""AI Patch Antenna_GPT_R3-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ic3GuLVhXL0Rc3VHbVIODD1M_P_ciq9q
"""

# ====================================================
# 0) INSTALLS (Colab only - run once)
# ====================================================
# (No external packages needed beyond standard Colab stack)
# You can leave this cell empty or use it for Drive mounting if needed, e.g.:
# from google.colab import drive
# drive.mount('/content/drive')

# ====================================================
# 1) CONFIGURATION
#    All variables are defined here
# ====================================================

import types

CFG = types.SimpleNamespace()

# ---- Data paths / format ----
# Folder that contains your CSV files (each with 161 columns)
# Change this to your actual folder path (e.g. "/content/drive/MyDrive/patch_data")
CFG.data_dir        = "/content"   # <-- EDIT THIS
CFG.csv_pattern     = "*.csv"           # all CSVs in data_dir will be loaded and concatenated

# Data layout
CFG.grid_h          = 10
CFG.grid_w          = 10
CFG.in_dim          = CFG.grid_h * CFG.grid_w  # 100 geometry bits
CFG.out_dim         = 61                       # real S11 values (cols 101..161)

# Train/val split
CFG.val_ratio       = 0.2
CFG.shuffle_data    = True
CFG.random_seed     = 42

# Training hyperparameters
CFG.batch_size      = 32
CFG.num_epochs      = 40
CFG.learning_rate   = 1e-3
CFG.weight_decay    = 1e-4

# Model hyperparameters
CFG.d_model         = 128        # latent dimension
CFG.cnn_channels    = [32, 64, 128]  # CNN encoder channels
CFG.num_decoder_layers = 4
CFG.n_heads         = 8          # (not used in the simplified FEDformer block here but kept for config)
CFG.dropout         = 0.1
CFG.fourier_modes   = 16         # how many low-frequency modes to keep

# Augmentation config (on INPUT geometry only)
CFG.use_augmentation = True      # turn on/off all augmentation
CFG.bit_flip_prob    = 0.05      # probability of flipping each bit (0 <-> 1)
CFG.noise_std        = 0.10      # Gaussian noise std added to input, then clipped to [0,1]

# Device
import torch
CFG.device          = "cuda" if torch.cuda.is_available() else "cpu"

CFG

# ====================================================
# 2) IMPORTS & SEEDING
# ====================================================

import os, glob, random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from sklearn.model_selection import train_test_split

# Reproducibility
def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

set_seed(CFG.random_seed)

print("Using device:", CFG.device)

# ====================================================
# 3) LOAD & INSPECT DATA
#    - Reads all CSVs in CFG.data_dir matching CFG.csv_pattern
#    - Concatenates into one DataFrame
#    - Splits into X (geometry) and y (S11 real values)
# ====================================================

# Collect all CSV file paths
csv_files = sorted(glob.glob(os.path.join(CFG.data_dir, CFG.csv_pattern)))
print("Found CSV files:", csv_files)

if len(csv_files) == 0:
    raise FileNotFoundError(
        f"No CSV files found in {CFG.data_dir}. "
        "Please upload your data and update CFG.data_dir."
    )

# Read and concatenate
df_list = []
for f in csv_files:
    df_part = pd.read_csv(f, header=None)  # no header assumed
    df_list.append(df_part)

df = pd.concat(df_list, axis=0, ignore_index=True)
print(f"Combined data shape: {df.shape}")

# Quick sanity check on column count
if df.shape[1] != (CFG.in_dim + CFG.out_dim):
    raise ValueError(
        f"Expected {CFG.in_dim + CFG.out_dim} columns (100 geom + 61 S11), "
        f"but got {df.shape[1]}"
    )

print("\nFirst 5 rows of raw data:")
display(df.head())

# Split into input (geometry) and output (S11 real)
geom_df = df.iloc[:, :CFG.in_dim]
s11_df  = df.iloc[:, CFG.in_dim:CFG.in_dim + CFG.out_dim]

print("\nGeometry subset shape:", geom_df.shape)
print("S11 real subset shape:", s11_df.shape)

print("\nGeometry (first row, first 20 bits):")
print(geom_df.iloc[0, :20].values)

print("\nS11 real values (first row):")
print(s11_df.iloc[0].values)

# Convert to numpy arrays
X_all = geom_df.values.astype(np.float32)
y_all = s11_df.values.astype(np.float32)

print("\nNumpy shapes -> X_all:", X_all.shape, ", y_all:", y_all.shape)

# ====================================================
# 4) TRAIN / VAL SPLIT
# ====================================================

X_train, X_val, y_train, y_val = train_test_split(
    X_all,
    y_all,
    test_size=CFG.val_ratio,
    random_state=CFG.random_seed,
    shuffle=CFG.shuffle_data,
)

print("Train X shape:", X_train.shape, "Train y shape:", y_train.shape)
print("Val   X shape:", X_val.shape, "Val   y shape:", y_val.shape)

# ====================================================
# 5) DATASET WITH OPTIONAL AUGMENTATION ON INPUT X
# ====================================================

class PatchAntennaDataset(Dataset):
    def __init__(self, X, y, cfg, split="train"):
        self.X = X
        self.y = y
        self.cfg = cfg
        self.split = split

    def __len__(self):
        return self.X.shape[0]

    def _augment(self, x):
        """
        x: np.array of shape (in_dim,)
        Apply:
        - bit flipping with probability cfg.bit_flip_prob
        - Gaussian noise with std cfg.noise_std (then clip to [0, 1])
        """
        # Bit-flip augmentation (0 <-> 1)
        if self.cfg.bit_flip_prob > 0:
            mask = np.random.rand(*x.shape) < self.cfg.bit_flip_prob
            x[mask] = 1.0 - x[mask]

        # Add noise
        if self.cfg.noise_std > 0:
            noise = np.random.normal(loc=0.0, scale=self.cfg.noise_std, size=x.shape)
            x = x + noise
            x = np.clip(x, 0.0, 1.0)

        return x

    def __getitem__(self, idx):
        x = self.X[idx].copy()
        y = self.y[idx].copy()

        # Only apply augmentation on training set and if enabled
        if self.split == "train" and self.cfg.use_augmentation:
            x = self._augment(x)

        # Reshape input to (1, H, W) for CNN
        x = x.reshape(self.cfg.grid_h, self.cfg.grid_w)
        x = np.expand_dims(x, axis=0)  # (1, H, W)

        x_tensor = torch.from_numpy(x).float()
        y_tensor = torch.from_numpy(y).float()

        return x_tensor, y_tensor

# Create datasets
train_dataset = PatchAntennaDataset(X_train, y_train, CFG, split="train")
val_dataset   = PatchAntennaDataset(X_val,   y_val,   CFG, split="val")

# Create dataloaders
train_loader = DataLoader(train_dataset, batch_size=CFG.batch_size, shuffle=True)
val_loader   = DataLoader(val_dataset,   batch_size=CFG.batch_size, shuffle=False)

# Show a small sample batch to validate shapes
sample_x, sample_y = next(iter(train_loader))
print("Sample batch X shape:", sample_x.shape)  # (B, 1, H, W)
print("Sample batch y shape:", sample_y.shape)  # (B, out_dim)

print("\nSample X[0] 10x10 patch:")
print(sample_x[0, 0].numpy())

print("\nSample y[0] first 10 S11 real values:")
print(sample_y[0, :10].numpy())

# ====================================================
# 6) MODEL DEFINITIONS
#    CNN Encoder + FEDformer-style Decoder
# ====================================================

class CNNEncoder(nn.Module):
    """
    Simple CNN encoder that converts a 10x10 geometry (1x10x10) to a latent vector (d_model).
    """
    def __init__(self, cfg):
        super().__init__()
        c1, c2, c3 = cfg.cnn_channels
        self.features = nn.Sequential(
            nn.Conv2d(1,  c1, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),           # 10x10 -> 5x5
            nn.Conv2d(c1, c2, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),           # 5x5 -> 2x2 (floor)
            nn.Conv2d(c2, c3, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.AdaptiveAvgPool2d((1,1))  # global pooling -> (B, c3, 1, 1)
        )
        # we'll infer the flattened size with a dummy forward
        dummy = torch.zeros(1, 1, cfg.grid_h, cfg.grid_w)
        with torch.no_grad():
            out = self.features(dummy)
        flat_dim = out.view(1, -1).shape[1]

        self.fc = nn.Linear(flat_dim, cfg.d_model)

    def forward(self, x):
        # x: (B,1,H,W)
        h = self.features(x)          # (B,c3,1,1)
        h = h.view(h.size(0), -1)     # (B,c3)
        z = self.fc(h)                # (B,d_model)
        return z


class FEDformerBlock(nn.Module):
    """
    Very simplified FEDformer-style block:
    - Applies Fourier transform along sequence length (frequency index)
    - Keeps low-frequency modes and applies learnable complex weights
    - Adds encoder conditioning and a feed-forward network
    NOTE: This is not a full replication of the original FEDformer paper,
          but a lightweight spectral mixing decoder block.
    """
    def __init__(self, cfg):
        super().__init__()
        self.d_model = cfg.d_model
        self.fourier_modes = cfg.fourier_modes

        # Complex weights for each low-frequency mode
        # We'll store as real and imaginary parts
        self.weight_real = nn.Parameter(torch.randn(self.fourier_modes, self.d_model) * 0.01)
        self.weight_imag = nn.Parameter(torch.randn(self.fourier_modes, self.d_model) * 0.01)

        # Feed-forward layers
        self.ffn = nn.Sequential(
            nn.LayerNorm(self.d_model),
            nn.Linear(self.d_model, 4 * self.d_model),
            nn.GELU(),
            nn.Dropout(cfg.dropout),
            nn.Linear(4 * self.d_model, self.d_model),
            nn.Dropout(cfg.dropout),
        )

    def forward(self, x, enc):
        """
        x:   (B, L, D) sequence of embeddings (one per frequency point)
        enc: (B, D)    encoder latent vector
        """
        B, L, D = x.shape

        # --- Fourier Transform along length dimension ---
        x_fft = torch.fft.rfft(x, dim=1)      # (B, L_fft, D) complex
        L_fft = x_fft.size(1)
        m = min(self.fourier_modes, L_fft)

        # Apply learnable complex weights to first m modes
        w_real = self.weight_real[:m]         # (m, D)
        w_imag = self.weight_imag[:m]         # (m, D)
        w_complex = torch.complex(w_real, w_imag)  # (m, D)

        x_fft_low = x_fft[:, :m, :]           # (B, m, D)
        x_fft_low = x_fft_low * w_complex     # broadcasted complex mul

        # Reconstruct a new FFT tensor (zeros for higher modes)
        new_fft = torch.zeros_like(x_fft)
        new_fft[:, :m, :] = x_fft_low

        # Inverse FFT back to time domain (length L)
        x_ifft = torch.fft.irfft(new_fft, n=L, dim=1)  # (B, L, D) real

        # --- Encoder conditioning: add encoder token to each position ---
        enc_expanded = enc.unsqueeze(1)  # (B,1,D)
        x_cond = x_ifft + enc_expanded   # (B,L,D)

        # --- Feed-forward network with residual connection ---
        out = x_cond + self.ffn(x_cond)  # (B,L,D)
        return out


class FEDformerDecoder(nn.Module):
    """
    Decoder that:
    - Creates a learned embedding for each frequency index (61 positions).
    - Passes through a stack of FEDformerBlocks, conditioned on encoder output.
    - Projects to real S11 values.
    """
    def __init__(self, cfg):
        super().__init__()
        self.cfg = cfg
        self.d_model = cfg.d_model
        self.out_dim = cfg.out_dim

        # Embedding for frequency positions (0..out_dim-1)
        self.freq_embed = nn.Embedding(cfg.out_dim, cfg.d_model)

        # Stack of FEDformer blocks
        self.blocks = nn.ModuleList([
            FEDformerBlock(cfg) for _ in range(cfg.num_decoder_layers)
        ])

        self.norm = nn.LayerNorm(cfg.d_model)
        self.head = nn.Linear(cfg.d_model, 1)  # output one real value per position

    def forward(self, enc):
        """
        enc: (B, D) encoder latent
        returns: (B, out_dim)
        """
        B = enc.size(0)
        device = enc.device

        # Frequency index tokens: [0,1,...,out_dim-1]
        freq_idx = torch.arange(self.out_dim, device=device).unsqueeze(0).repeat(B, 1)  # (B,L)
        x = self.freq_embed(freq_idx)  # (B,L,D)

        # Pass through FEDformer blocks
        for block in self.blocks:
            x = block(x, enc)          # (B,L,D)

        x = self.norm(x)
        out = self.head(x).squeeze(-1)  # (B,L)
        return out


class PatchAntennaModel(nn.Module):
    """
    Full model: CNNEncoder -> FEDformerDecoder
    """
    def __init__(self, cfg):
        super().__init__()
        self.encoder = CNNEncoder(cfg)
        self.decoder = FEDformerDecoder(cfg)

    def forward(self, x):
        # x: (B,1,H,W)
        enc_latent = self.encoder(x)       # (B,D)
        out = self.decoder(enc_latent)     # (B,out_dim)
        return out


# Instantiate and test on a sample batch
model = PatchAntennaModel(CFG).to(CFG.device)
print(model)

test_x, _ = next(iter(train_loader))
test_x = test_x.to(CFG.device)
with torch.no_grad():
    test_out = model(test_x)
print("\nModel output shape for sample batch:", test_out.shape)

# ====================================================
# 7) TRAINING UTILITIES
# ====================================================

criterion = nn.MSELoss()
optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=CFG.learning_rate,
    weight_decay=CFG.weight_decay
)

def train_one_epoch(model, loader, optimizer, device):
    model.train()
    running_loss = 0.0
    for x, y in loader:
        x = x.to(device)
        y = y.to(device)

        optimizer.zero_grad()
        preds = model(x)
        loss = criterion(preds, y)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * x.size(0)

    return running_loss / len(loader.dataset)


def eval_one_epoch(model, loader, device):
    model.eval()
    running_loss = 0.0
    with torch.no_grad():
        for x, y in loader:
            x = x.to(device)
            y = y.to(device)

            preds = model(x)
            loss = criterion(preds, y)
            running_loss += loss.item() * x.size(0)

    return running_loss / len(loader.dataset)

# ====================================================
# 8) TRAINING LOOP
#    - Trains model
#    - Records train/val loss per epoch
#    - Prints progress
# ====================================================

train_losses = []
val_losses = []

best_val_loss = float("inf")
best_state_dict = None

for epoch in range(1, CFG.num_epochs + 1):
    train_loss = train_one_epoch(model, train_loader, optimizer, CFG.device)
    val_loss   = eval_one_epoch(model, val_loader, CFG.device)

    train_losses.append(train_loss)
    val_losses.append(val_loss)

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        best_state_dict = {k: v.cpu().clone() for k, v in model.state_dict().items()}

    print(f"Epoch {epoch:03d} | Train Loss: {train_loss:.6f} | Val Loss: {val_loss:.6f}")

# Load best weights (based on val loss)
if best_state_dict is not None:
    model.load_state_dict(best_state_dict)
    model.to(CFG.device)
    print("\nLoaded best model (val_loss = {:.6f})".format(best_val_loss))

# ====================================================
# 9) LOSS CURVES
# ====================================================

plt.figure(figsize=(7,5))
plt.plot(train_losses, label="Train Loss")
plt.plot(val_losses,   label="Val Loss")
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.title("Training / Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

# ====================================================
# 10) SAMPLE PREDICTIONS ON VALIDATION SET
#     To validate numerical behavior
# ====================================================

model.eval()
val_iter = iter(val_loader)
x_val_batch, y_val_batch = next(val_iter)
x_val_batch = x_val_batch.to(CFG.device)
y_val_batch = y_val_batch.to(CFG.device)

with torch.no_grad():
    y_pred_batch = model(x_val_batch)

# Convert to CPU numpy for inspection
y_true = y_val_batch.cpu().numpy()
y_pred = y_pred_batch.cpu().numpy()

# Show first few samples (first few frequency points only to keep table small)
n_show = min(3, y_true.shape[0])
freqs_to_show = 10  # first 10 frequency points

for i in range(n_show):
    print(f"\n==== Validation sample {i} ====")
    df_compare = pd.DataFrame({
        "S11_true": y_true[i, :freqs_to_show],
        "S11_pred": y_pred[i, :freqs_to_show],
    })
    display(df_compare)

# ====================================================
# 11) INFERENCE: NEW GEOMETRY -> PREDICT S11 (REAL VALUES)
# ====================================================

def predict_s11_for_geometry(model, geom_bits_flat, cfg: types.SimpleNamespace):
    """
    geom_bits_flat: 1D array-like of length cfg.in_dim (100 bits 0/1)
    returns: np.array of shape (out_dim,) with predicted real S11 values
    """
    model.eval()
    geom_bits_flat = np.array(geom_bits_flat, dtype=np.float32)

    if geom_bits_flat.shape[0] != cfg.in_dim:
        raise ValueError(f"Expected geometry length {cfg.in_dim}, got {geom_bits_flat.shape[0]}")

    # reshape to (1,1,H,W)
    x = geom_bits_flat.reshape(cfg.grid_h, cfg.grid_w)
    x = np.expand_dims(x, axis=(0,1))   # (1,1,H,W)
    x_tensor = torch.from_numpy(x).float().to(cfg.device)

    with torch.no_grad():
        y_pred = model(x_tensor)        # (1,out_dim)

    return y_pred.cpu().numpy().reshape(-1)


# ---- Example usage #1: from an existing validation sample ----
example_x, _ = val_dataset[0]
example_geom_flat = example_x[0].numpy().reshape(-1)  # (100,)
print("Example geometry bits (first 20):", example_geom_flat[:20])

pred_s11 = predict_s11_for_geometry(model, example_geom_flat, CFG)
print("\nPredicted S11 (first 10 values):")
print(pred_s11[:10])

# ---- Example usage #2: from a manually defined geometry ----
# Replace this with your own 0/1 geometry of length 100:
manual_geom_bits = np.random.randint(0, 2, size=(CFG.in_dim,))
pred_s11_manual = predict_s11_for_geometry(model, manual_geom_bits, CFG)
print("\nManual geometry prediction (first 10 values):")
print(pred_s11_manual[:10])

# ====================================================
# 12) OPTIONAL: SIMPLE TEXT INPUT INTERFACE (MANUAL)
# ====================================================
# You can run this cell and paste 100 comma-separated 0/1 values
# into the input prompt in Colab to get predictions.

def ask_and_predict(model, cfg):
    print(f"Please enter {cfg.in_dim} comma-separated bits (0 or 1).")
    s = input().strip()
    bits_str = s.split(",")
    if len(bits_str) != cfg.in_dim:
        print(f"Error: you entered {len(bits_str)} values, expected {cfg.in_dim}.")
        return

    geom = np.array([float(b) for b in bits_str], dtype=np.float32)
    y_pred = predict_s11_for_geometry(model, geom, cfg)
    print("\nPredicted S11 values (all 61 points):")
    print(y_pred)

# Uncomment to use:
# ask_and_predict(model, CFG)