fclose('all'); % Force close any stuck files
clear all; clc; close all;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%% Variables entered by user %%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

x_grid_div = 10; 
y_grid_div = 10; 
num_arr = 15000; % Max ID of the antenna

% UPDATE THESE AS NEEDED
start_patch = 19001; 
stop_patch = 20000; 

grid_sq_dim = 10; 
feed_x_dim = 2.96; 
feed_y_dim = 25; 

substrate_x_dim = 150; 
substrate_y_dim = 150; 
substrate_h = 1.57; 
substrate_er = 4.4; 

ground_x_dim = substrate_x_dim; 
ground_y_dim = substrate_y_dim; 

patch_offset_x = 25; 
patch_offset_y = 25; 

% Export Path for CSV results
export_path = 'C:/Users/zhuomanf/Downloads/'; 

% Input CSV Path
input_csv = 'C:\Users\zhuomanf\Downloads\\patch_antennas_updated3.csv';

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% LOAD AND CLEAN DATA 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

fprintf('Reading CSV file: %s\n', input_csv);
raw_data = readmatrix(input_csv);
clean_data = raw_data(~any(isnan(raw_data), 2), :);

rows_loaded = size(clean_data, 1);
num_loaded = rows_loaded / y_grid_div; 

fprintf('Loaded %d antennas from CSV.\n', num_loaded);

loaded_patches = permute(reshape(clean_data', x_grid_div, y_grid_div, num_loaded), [2 1 3]);

% Ensure array size
if num_loaded > num_arr
    num_arr = num_loaded;
end
patch_ant = zeros(y_grid_div, x_grid_div, num_arr);

% Map data starting at index 1
file_start_id = 1; 
file_end_id = file_start_id + num_loaded - 1;

patch_ant(:, :, file_start_id:file_end_id) = loaded_patches;
fprintf('Data mapped. Ready to generate Python script.\n');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%% Opens Python file to write to %%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

PyScript_name = strcat('C:\Users\zhuomanf\Downloads\patch_antenna_test_',num2str(start_patch),'-',num2str(stop_patch),'.py');
fid = fopen(PyScript_name,'w');

if fid == -1
    error('Could not create Python file. Check directory permissions.');
end

try
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%% Setup Python Headers (COM Connection Method) %%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    fprintf(fid, '# ----------------------------------------------\n');
    fprintf(fid, '# HFSS Python Automation Script\n');
    fprintf(fid, '# Generated by MATLAB\n');
    fprintf(fid, '# ----------------------------------------------\n');
    fprintf(fid, 'import time\n');
    fprintf(fid, 'import sys\n');
    % We import System to use the Windows COM activator (Same method as VBScript)
    fprintf(fid, 'import System\n\n');
    
    % --- COM INITIALIZATION BLOCK ---
    % This is the most robust method. It ignores Python paths and asks Windows for the running App.
    fprintf(fid, 'print("Initializing via System Activator...")\n');
    fprintf(fid, 'try:\n');
    fprintf(fid, '    # First check if oDesktop exists globally (Internal Shell)\n');
    fprintf(fid, '    oDesktop.RestoreWindow()\n');
    fprintf(fid, 'except:\n');
    fprintf(fid, '    # If not, create connection via ProgID (Mimics VBScript CreateObject)\n');
    fprintf(fid, '    type_handle = System.Type.GetTypeFromProgID("Ansoft.ElectronicsDesktop")\n');
    fprintf(fid, '    oAnsoftApp = System.Activator.CreateInstance(type_handle)\n');
    fprintf(fid, '    oDesktop = oAnsoftApp.GetAppDesktop()\n');
    fprintf(fid, '    oDesktop.RestoreWindow()\n\n');

    % START OF ANTENNA LOOP
    for patch_num = start_patch:1:stop_patch        
            
            fprintf(fid, 'print("Processing Antenna: Patch_%d")\n', patch_num);
            
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        
            %%%%%%%%%%% Create NEW Project and Design %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            
            fprintf(fid, 'oProject = oDesktop.NewProject()\n');
            fprintf(fid, 'oProject.InsertDesign("HFSS", "Patch%d", "HFSS Modal Network", "")\n', patch_num);
            fprintf(fid, 'oDesign = oProject.SetActiveDesign("Patch%d")\n', patch_num);
            fprintf(fid, 'oDesign.SetSolutionType("HFSS Modal Network", ["NAME:Options", "EnableAutoOpen:=", False])\n');
            fprintf(fid, 'oEditor = oDesign.SetActiveEditor("3D Modeler")\n');
            
            % Close windows to save RAM
            fprintf(fid, 'oDesktop.CloseAllWindows()\n');
            
            fprintf(fid, 'oDefinitionManager = oProject.GetDefinitionManager()\n');
            fprintf(fid, 'oModule = oDesign.GetModule("BoundarySetup")\n\n');

            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        
            %%%%%%%%% Geometry & Materials %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            
            % Material
            fprintf(fid, 'oDefinitionManager.AddMaterial(["NAME:Patch_Substrate", "CoordinateSystemType:=", "Cartesian", "BulkOrSurfaceType:=", 1, ["NAME:PhysicsTypes", "set:=", ["Electromagnetic"]], "permittivity:=", "%s"])\n', num2str(substrate_er));

            % Substrate Box
            fprintf(fid, 'oEditor.CreateBox(["NAME:BoxParameters", "IsCovered:=", True, "XPosition:=", "%smm", "YPosition:=", "%smm", "ZPosition:=", "0mm", "XSize:=", "%smm", "YSize:=", "%smm", "ZSize:=", "%smm"], ["NAME:Attributes", "Name:=", "substrate", "Flags:=", "", "Color:=", "(255 255 0)", "Transparency:=", 0, "PartCoordinateSystem:=", "Global", "MaterialValue:=", "\\"Patch_Substrate\\"", "SolveInside:=", True])\n', ...
                num2str(-patch_offset_x), num2str(-patch_offset_y), num2str(substrate_x_dim), num2str(substrate_y_dim), num2str(-substrate_h));

            % Ground Plate
            fprintf(fid, 'oEditor.CreateRectangle(["NAME:RectangleParameters", "IsCovered:=", True, "XStart:=", "%smm", "YStart:=", "%smm", "ZStart:=", "%smm", "Width:=", "%smm", "Height:=", "%smm", "WhichAxis:=", "Z"], ["NAME:Attributes", "Name:=", "ground_plate", "Flags:=", "", "Color:=", "(143 175 143)", "Transparency:=", 0, "PartCoordinateSystem:=", "Global", "MaterialValue:=", "\\"vacuum\\""])\n', ...
                num2str(-patch_offset_x), num2str(-patch_offset_y), num2str(-substrate_h), num2str(ground_x_dim), num2str(ground_y_dim));
            fprintf(fid, 'oModule.AssignPerfectE(["NAME:ground_plate_PEC", "Objects:=", ["ground_plate"], "InfGroundPlane:=", False])\n');

            % Feed
            fprintf(fid, 'oEditor.CreateRectangle(["NAME:RectangleParameters", "IsCovered:=", True, "XStart:=", "48.52mm", "YStart:=", "-25mm", "ZStart:=", "0mm", "Width:=", "%smm", "Height:=", "%smm", "WhichAxis:=", "Z"], ["NAME:Attributes", "Name:=", "feed", "Flags:=", "", "Color:=", "(143 175 143)", "Transparency:=", 0, "PartCoordinateSystem:=", "Global", "MaterialValue:=", "\\"vacuum\\""])\n', ...
                num2str(feed_x_dim), num2str(feed_y_dim));
            fprintf(fid, 'oModule.AssignPerfectE(["NAME:Feed_PEC", "Objects:=", ["feed"], "InfGroundPlane:=", False])\n');

            % Port
            fprintf(fid, 'oEditor.CreateRectangle(["NAME:RectangleParameters", "IsCovered:=", True, "XStart:=", "48.52mm", "YStart:=", "-25mm", "ZStart:=", "0mm", "Width:=", "%smm", "Height:=", "%smm", "WhichAxis:=", "Y"], ["NAME:Attributes", "Name:=", "port", "Flags:=", "", "Color:=", "(143 175 143)", "Transparency:=", 0, "PartCoordinateSystem:=", "Global", "MaterialValue:=", "\\"vacuum\\""])\n', ...
                num2str(-substrate_h), num2str(feed_x_dim));
            fprintf(fid, 'oModule.AssignPerfectE(["NAME:port_PEC", "Objects:=", ["port"], "InfGroundPlane:=", False])\n');
            
            % Lumped Port Excitation
            fprintf(fid, 'oModule.AssignLumpedPort(["NAME:1", "Objects:=", ["port"], "LumpedPortType:=", "Default", "DoDeembed:=", False, ["NAME:Modes", ["NAME:Mode1", "ModeNum:=", 1, "UseIntLine:=", True, ["NAME:IntLine", "Coordinate System:=", "Global", "Start:=", ["50mm", "-25mm", "-1.57mm"], "End:=", ["50mm", "-25mm", "0mm"]], "AlignmentGroup:=", 0, "CharImp:=", "Zpi", "RenormImp:=", "50ohm"]], "Impedance:=", "50ohm"])\n');

            % Airbox & Radiation
            fprintf(fid, 'oEditor.CreateBox(["NAME:BoxParameters", "IsCovered:=", True, "XPosition:=", "-75mm", "YPosition:=", "-75mm", "ZPosition:=", "-50mm", "XSize:=", "250mm", "YSize:=", "250mm", "ZSize:=", "100mm"], ["NAME:Attributes", "Name:=", "AirBox", "Flags:=", "", "Color:=", "(255 0 255)", "Transparency:=", 0.75, "PartCoordinateSystem:=", "Global", "MaterialValue:=", "\\"vacuum\\""])\n');
            fprintf(fid, 'oModule.AssignRadiation(["NAME:Rad1", "Objects:=", ["AirBox"]])\n\n');

            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        
            %%%%%%%% Grid Generation %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            
            % Create Base Grid Square
            fprintf(fid, 'oEditor.CreateRectangle(["NAME:RectangleParameters", "IsCovered:=", True, "XStart:=", "%smm", "YStart:=", "%smm", "ZStart:=", "0mm", "Width:=", "%smm", "Height:=", "%smm", "WhichAxis:=", "Z"], ["NAME:Attributes", "Name:=", "grid_sq", "Flags:=", "", "Color:=", "(143 175 143)", "Transparency:=", 0, "PartCoordinateSystem:=", "Global", "MaterialValue:=", "\\"vacuum\\""])\n', ...
                num2str(-grid_sq_dim./2), num2str(-grid_sq_dim./2), num2str(grid_sq_dim), num2str(grid_sq_dim));

            grid_sq_num = 1;
            for y = 1:1:y_grid_div
                for x = 1:1:x_grid_div
                    if patch_ant(y,x,patch_num) == 1
                        x_pos = (x.*grid_sq_dim) - (grid_sq_dim./2);
                        y_pos = (y.*grid_sq_dim) - (grid_sq_dim./2);
                        
                        % Duplicate
                        fprintf(fid, 'oEditor.DuplicateAlongLine(["NAME:Selections", "Selections:=", "grid_sq", "NewPartsModelFlag:=", "Model"], ["NAME:DuplicateToAlongLineParameters", "CreateNewObjects:=", True, "XComponent:=", "%smm", "YComponent:=", "%smm", "ZComponent:=", "0mm", "NumClones:=", "2"], ["NAME:Options", "DuplicateAssignments:=", True], ["CreateGroupsForNewObjects:=", False])\n', ...
                            num2str(x_pos), num2str(y_pos));
                        
                        % Assign PEC 
                        fprintf(fid, 'oModule.AssignPerfectE(["NAME:grid_sq_%d_PEC", "Objects:=", ["grid_sq_%d"], "InfGroundPlane:=", False])\n', ...
                            grid_sq_num, grid_sq_num);
                        
                        grid_sq_num = grid_sq_num + 1;
                    end
                end
            end
            
            % Delete the base square
            fprintf(fid, 'oEditor.Delete(["NAME:Selections", "Selections:=", "grid_sq"])\n');
            
            fprintf(fid, 'time.sleep(2)\n'); 

            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        
            %%%%%%%% Setup and Sweep %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

            fprintf(fid, 'oModule = oDesign.GetModule("AnalysisSetup")\n');
            fprintf(fid, 'oModule.InsertSetup("HfssDriven", ["NAME:Setup1", "SolveType:=", "Single", "Frequency:=", "3GHz", "MaxDeltaS:=", 0.02, "UseMatrixConv:=", False, "MaximumPasses:=", 20, "MinimumPasses:=", 1, "MinimumConvergedPasses:=", 1, "PercentRefinement:=", 30, "IsEnabled:=", True, ["NAME:MeshLink", "ImportMesh:=", False], "BasisOrder:=", 1, "DoLambdaRefine:=", True, "DoMaterialLambda:=", True, "SetLambdaTarget:=", False, "Target:=", 0.3333, "UseMaxTetIncrease:=", False, "PortAccuracy:=", 2, "UseABCOnPort:=", False, "SetPortMinMaxTri:=", False, "DrivenSolverType:=", "Direct Solver", "EnhancedLowFreqAccuracy:=", False, "SaveRadFieldsOnly:=", False, "SaveAnyFields:=", True, "CacheSaveKind:=", "Delta", "ConstantDelta:=", "0s", "IESolverType:=", "Auto", "LambdaTargetForIESolver:=", 0.15, "UseDefaultLambdaTgtForIESolver:=", True, "IE Solver Accuracy:=", "Balanced", "InfiniteSphereSetup:=", "", "MaxPass:=", 10, "MinPass:=", 1, "MinConvPass:=", 1, "PerError:=", 1, "PerRefine:=", 30])\n');
            fprintf(fid, 'oModule.InsertFrequencySweep("Setup1", ["NAME:Sweep", "IsEnabled:=", True, "RangeType:=", "LinearCount", "RangeStart:=", "1GHz", "RangeEnd:=", "6GHz", "RangeCount:=", 61, "Type:=", "Discrete", "SaveFields:=", False, "SaveRadFields:=", False, "SMatrixOnlySolveMode:=", "Auto"])\n');

            % Save As
            fprintf(fid, 'oProject.SaveAs("Patch_%d.aedt", True)\n', patch_num);
            
            % Wait for Save
            fprintf(fid, 'time.sleep(15)\n'); 

            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        
            %%%%%%%% Analyze with Python Retry Logic %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            
            fprintf(fid, 'success = False\n');
            fprintf(fid, 'print("Attempting to Solve...")\n');
            fprintf(fid, 'for attempt in range(5):\n'); % Try 5 times
            fprintf(fid, '    try:\n');
            fprintf(fid, '        oDesign.AnalyzeAll()\n');
            fprintf(fid, '        success = True\n');
            fprintf(fid, '        print("Solve Successful")\n');
            fprintf(fid, '        break\n'); 
            fprintf(fid, '    except Exception as e:\n');
            fprintf(fid, '        print("Solve Failed (License or File lock). Waiting 60s...")\n');
            fprintf(fid, '        time.sleep(60)\n'); 
            
            % Pause after solve
            fprintf(fid, 'time.sleep(15)\n');

            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        
            %%%%%%%% Export Data %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            
            fprintf(fid, 'if success:\n');
            fprintf(fid, '    oModule = oDesign.GetModule("ReportSetup")\n');
            fprintf(fid, '    oModule.CreateReport("Patch%d_S11_plot", "Modal Solution Data", "Rectangular Plot", "Setup1 : Sweep", ["Domain:=", "Sweep"], ["Freq:=", ["All"]], ["X Component:=", "Freq", "Y Component:=", ["dB(S(1,1))"]])\n', patch_num);
            
            % Construct filename using the export path
            csv_filename = sprintf('%spatch_%d_s11_plot.csv', export_path, patch_num);
            
            fprintf(fid, '    oModule.ExportToFile("Patch%d_S11_plot", "%s", False)\n', patch_num, csv_filename);
            
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%        
            %%%%%%%% Cleanup %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

            fprintf(fid, 'oDesktop.CloseAllWindows()\n');
            fprintf(fid, 'time.sleep(3)\n');
            fprintf(fid, 'oProject.Save()\n');
            fprintf(fid, 'oProject.Close()\n\n');
            
    end
    % END OF ANTENNA LOOP

catch ME
    fclose(fid);
    rethrow(ME);
end

fclose(fid);
fprintf('Python script generation complete.\n');
fprintf('Please run %s inside HFSS via Tools > Run Script.\n', PyScript_name);